---
# tasks file for roles/database
  - name: Run Database
    docker_container:
      name: devops-database # le nom du container
      image: hipp0x/devops-database:latest # l'image sur laquelle on se base
      networks:
        - name: "app-network" # le nom du network auquel on se connecte
