---
# tasks file for roles/proxy
- name: Run Proxy
  docker_container:
    name: devops-server
    image: hipp0x/devops-server:latest
    state: started
    networks:
      - name: "app-network"
    ports:
      - "8080:80"