name: Publish Docker Images
on:
  workflow_run: # trigger only when "Backend Tests" are completed
    workflows: [Backend Tests]
    types: [completed]
    branches: [main] # trigger only on main branch

jobs:

  build-and-push-docker-image:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USR }} -p ${{ secrets.DOCKERHUB_PWD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./Backend
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USR}}/backend:1.0
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./DB
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USR}}/database:1.0
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./Serveur
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USR}}/serveur:1.0
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
